import type { CategorySchema } from "@/lib/intelligence/types";

/**
 * The camera category schema — dedicated, interchangeable-lens (mirrorless/
 * DSLR) cameras. Same role as `smartphone.ts`.
 *
 * `camera` here scores the sensor/image-capture specs themselves (the
 * product's whole purpose), unlike on a phone where it's one component among
 * several. Its megapixel attribute gets its own `camera_sensor_mp` key/band
 * rather than reusing a phone's `main_cam_mp` — a large-sensor camera at 24MP
 * outresolves a phone at 108MP because its individual pixels are so much
 * bigger, so the phone scale would rank it backwards. See reference.ts.
 */
export const cameraSchema: CategorySchema = {
  id: "camera",
  label: "Camera",
  shopifyProductTypes: ["Cameras"],
  groups: [
    { id: "camera", label: "Sensor & Image Quality" },
    { id: "performance", label: "Performance" },
    { id: "display", label: "Screen & Viewfinder" },
    { id: "battery", label: "Battery" },
    { id: "connectivity", label: "Connectivity" },
    { id: "build", label: "Build & Design" },
    { id: "software", label: "Software" },
  ],
  componentWeights: {
    camera: 0.3,
    performance: 0.16,
    features: 0.14,
    build: 0.14,
    battery: 0.12,
    display: 0.1,
    software: 0.02,
    value: 0.02,
  },
  attributes: [
    // --- Sensor & image quality -------------------------------------------
    {
      key: "camera_sensor_mp",
      label: "Resolution",
      hint: "Megapixels aren't the whole story — sensor size (below) matters at least as much for real image quality.",
      valueType: "number",
      unit: "mp",
      normalizer: "quantity",
      group: "camera",
      scoring: { component: "camera", weight: 2, higherIsBetter: true },
    },
    {
      key: "sensor_size",
      label: "Sensor size",
      hint: "A bigger sensor gathers more light per pixel — better low-light performance and background blur, regardless of megapixel count.",
      valueType: "enum",
      normalizer: "enum",
      enumValues: ["1-inch", "Micro Four Thirds", "APS-C", "Full-Frame"],
      enumRank: ["Full-Frame", "APS-C", "Micro Four Thirds", "1-inch"],
      group: "camera",
      scoring: { component: "camera", weight: 4, higherIsBetter: true },
    },
    {
      key: "camera_iso_max",
      label: "Max ISO (expanded)",
      hint: "How far the sensor's sensitivity can be pushed in the dark. Higher ceilings help in low light, at some cost to image noise.",
      valueType: "integer",
      unit: "iso",
      normalizer: "quantity",
      group: "camera",
      scoring: { component: "camera", weight: 1.5, higherIsBetter: true },
    },
    {
      key: "camera_af_points",
      label: "Autofocus points",
      hint: "More AF points generally means faster, more reliable focus tracking across the frame, including on moving subjects.",
      valueType: "integer",
      unit: "count",
      normalizer: "quantity",
      group: "camera",
      scoring: { component: "camera", weight: 1.5, higherIsBetter: true },
    },
    {
      key: "video_max_resolution",
      label: "Max video resolution",
      valueType: "enum",
      normalizer: "enum",
      enumValues: ["1080p", "4K", "6K", "8K"],
      enumRank: ["8K", "6K", "4K", "1080p"],
      group: "camera",
      scoring: { component: "camera", weight: 1, higherIsBetter: true },
    },
    // --- Performance ------------------------------------------------------
    {
      key: "camera_burst_fps",
      label: "Burst shooting speed",
      hint: "Frames per second in continuous shooting — how well it keeps up with fast action.",
      valueType: "number",
      unit: "fps",
      normalizer: "quantity",
      group: "performance",
      scoring: { component: "performance", weight: 3, higherIsBetter: true },
    },
    {
      key: "processor",
      label: "Image processor",
      valueType: "text",
      normalizer: "passthrough",
      group: "performance",
    },
    // --- Screen & viewfinder -----------------------------------------------
    {
      key: "screen_size_in",
      label: "Screen size",
      valueType: "number",
      unit: "in",
      normalizer: "quantity",
      group: "display",
    },
    {
      key: "camera_screen_dots",
      label: "Screen resolution",
      hint: "Dot count of the rear LCD. Higher makes reviewing shots and menus look sharper.",
      valueType: "integer",
      unit: "dots",
      normalizer: "quantity",
      group: "display",
      scoring: { component: "display", weight: 1.5, higherIsBetter: true },
    },
    {
      key: "articulating_screen",
      label: "Vari-angle/tilting screen",
      hint: "Whether the screen flips or tilts out — useful for vlogging, low/high angles and selfies.",
      valueType: "boolean",
      normalizer: "boolean",
      group: "display",
      scoring: { component: "display", weight: 1, higherIsBetter: true },
    },
    {
      key: "camera_viewfinder_dots",
      label: "Viewfinder resolution",
      hint: "Dot count of the electronic viewfinder, where fitted. Higher looks sharper and more like an optical finder.",
      valueType: "integer",
      unit: "dots",
      normalizer: "quantity",
      group: "display",
      scoring: { component: "display", weight: 1.5, higherIsBetter: true },
    },
    // --- Battery -----------------------------------------------------
    {
      key: "camera_shots_per_charge",
      label: "Battery life",
      hint: "CIPA-rated shots per charge — a standardised (and typically conservative) estimate, useful mainly for comparing models.",
      valueType: "integer",
      unit: "shots",
      normalizer: "quantity",
      group: "battery",
      scoring: { component: "battery", weight: 4, higherIsBetter: true },
    },
    {
      key: "battery_type",
      label: "Battery",
      valueType: "text",
      normalizer: "passthrough",
      group: "battery",
    },
    // --- Connectivity ----------------------------------------------
    {
      key: "wifi",
      label: "Wi-Fi",
      hint: "Built-in Wi-Fi for transferring photos to a phone or computer without a cable.",
      valueType: "boolean",
      normalizer: "boolean",
      group: "connectivity",
      scoring: { component: "features", weight: 1, higherIsBetter: true },
    },
    {
      key: "bluetooth",
      label: "Bluetooth",
      hint: "Low-power always-on link for remote control and quick pairing to the Wi-Fi transfer.",
      valueType: "boolean",
      normalizer: "boolean",
      group: "connectivity",
      scoring: { component: "features", weight: 0.5, higherIsBetter: true },
    },
    {
      key: "ibis",
      label: "In-body image stabilisation",
      hint: "Stabilises any lens attached, including older ones without their own stabilisation.",
      valueType: "boolean",
      normalizer: "boolean",
      group: "connectivity",
      scoring: { component: "features", weight: 2, higherIsBetter: true },
    },
    {
      key: "usb_standard",
      label: "USB port",
      valueType: "enum",
      normalizer: "enum",
      enumValues: ["Micro-USB", "USB-C", "USB 2.0", "USB 3.0", "USB 3.2"],
      group: "connectivity",
    },
    {
      key: "camera_card_slots",
      label: "Memory card slots",
      hint: "Two slots let you shoot to both cards at once for an instant backup.",
      valueType: "integer",
      unit: "count",
      normalizer: "quantity",
      group: "connectivity",
      scoring: { component: "features", weight: 1, higherIsBetter: true },
    },
    // --- Build ----------------------------------------------------
    {
      key: "camera_weight_g",
      label: "Weight",
      hint: "Body-only weight; add the lens for what you'll actually carry.",
      valueType: "number",
      unit: "g",
      normalizer: "quantity",
      group: "build",
      scoring: { component: "build", weight: 1.5, higherIsBetter: false },
    },
    {
      key: "lens_mount",
      label: "Lens mount",
      hint: "Which lenses fit. A bigger, more established mount ecosystem means more lens choice, new and used.",
      valueType: "text",
      normalizer: "passthrough",
      group: "build",
    },
    {
      key: "weather_sealed",
      label: "Weather sealing",
      hint: "Gasketing against dust and light moisture. Not the same as being waterproof.",
      valueType: "boolean",
      normalizer: "boolean",
      group: "build",
      scoring: { component: "build", weight: 2, higherIsBetter: true },
    },
    // --- Software ------------------------------------------------
    {
      key: "firmware_updatable",
      label: "Firmware updates",
      hint: "Whether the maker can add features or improve autofocus/video after purchase.",
      valueType: "boolean",
      normalizer: "boolean",
      group: "software",
      scoring: { component: "software", weight: 1, higherIsBetter: true },
    },
  ],
};
