import type { CategorySchema } from "@/lib/intelligence/types";

/**
 * The gaming console category schema — handheld/hybrid consoles (the
 * catalog's actual shape today). Same role as `smartphone.ts`.
 *
 * No lens, so `camera` is left unscored — same precedent as `smartphone.ts`
 * leaving `value` unscored. The main SoC (`soc`) is deliberately NOT scored
 * via a lookup table the way a phone/laptop chip is: a console SoC (e.g. a
 * custom Nvidia Ampere part) isn't on a comparable scale to either of those,
 * and with a single console in the catalog so far there's no real basis for
 * inventing one — same discipline as leaving an under-evidenced attribute
 * unscored rather than guessing a number, per provenance.ts's "never
 * invented" rule.
 */
export const gamingConsoleSchema: CategorySchema = {
  id: "gaming_console",
  label: "Gaming Console",
  shopifyProductTypes: ["Gaming Consoles"],
  groups: [
    { id: "performance", label: "Performance" },
    { id: "display", label: "Display" },
    { id: "battery", label: "Battery & Charging" },
    { id: "connectivity", label: "Connectivity" },
    { id: "build", label: "Build & Design" },
    { id: "software", label: "Software" },
  ],
  componentWeights: {
    performance: 0.22,
    features: 0.18,
    display: 0.18,
    battery: 0.16,
    build: 0.14,
    software: 0.06,
    camera: 0.03,
    value: 0.03,
  },
  attributes: [
    // --- Performance ------------------------------------------------------
    {
      key: "soc",
      label: "Chip",
      hint: "The custom chip that runs the console. Faster chips hold higher resolution/framerate without dropping frames.",
      valueType: "text",
      normalizer: "passthrough",
      group: "performance",
    },
    {
      key: "gpu_cuda_cores",
      label: "GPU cores",
      valueType: "integer",
      unit: "cores",
      normalizer: "quantity",
      group: "performance",
    },
    {
      key: "console_ram_gb",
      label: "RAM",
      hint: "Working memory shared between the system and the running game.",
      valueType: "integer",
      unit: "gb",
      normalizer: "storage",
      group: "performance",
      scoring: { component: "performance", weight: 3, higherIsBetter: true },
    },
    {
      key: "console_storage_gb",
      label: "Storage",
      hint: "Built-in space for installed games. Most consoles support adding more via a memory card.",
      valueType: "integer",
      unit: "gb",
      normalizer: "storage",
      group: "performance",
      scoring: { component: "features", weight: 1.5, higherIsBetter: true },
    },
    {
      key: "storage_type",
      label: "Storage type",
      valueType: "enum",
      normalizer: "enum",
      enumValues: ["eMMC", "UFS", "SSD"],
      enumRank: ["SSD", "UFS", "eMMC"],
      group: "performance",
      scoring: { component: "features", weight: 0.5, higherIsBetter: true },
    },
    // --- Display ---------------------------------------------------------
    {
      key: "display_size_in",
      label: "Screen size",
      hint: "Built-in handheld screen size. Bigger is easier to see; smaller is lighter and more pocketable.",
      valueType: "number",
      unit: "in",
      normalizer: "quantity",
      group: "display",
    },
    {
      key: "display_tech",
      label: "Display type",
      hint: "OLED panels have deeper blacks and better contrast than LCD.",
      valueType: "enum",
      normalizer: "enum",
      enumValues: ["LCD", "OLED"],
      enumRank: ["OLED", "LCD"],
      group: "display",
      scoring: { component: "display", weight: 2, higherIsBetter: true },
    },
    {
      key: "display_resolution",
      label: "Handheld resolution",
      valueType: "text",
      normalizer: "resolution",
      group: "display",
    },
    {
      key: "refresh_rate_hz",
      label: "Refresh rate",
      hint: "How many times a second the screen redraws. Higher makes fast-moving games look smoother.",
      valueType: "integer",
      unit: "hz",
      normalizer: "quantity",
      group: "display",
      scoring: { component: "display", weight: 1.5, higherIsBetter: true },
    },
    {
      key: "max_output_resolution",
      label: "Max docked/TV output",
      hint: "The sharpest picture it can output to a TV when docked, separate from the handheld screen's own resolution.",
      valueType: "enum",
      normalizer: "enum",
      enumValues: ["720p", "1080p", "4K"],
      enumRank: ["4K", "1080p", "720p"],
      group: "display",
      scoring: { component: "display", weight: 1.5, higherIsBetter: true },
    },
    // --- Battery -----------------------------------------------------
    {
      key: "console_battery_mah",
      label: "Battery capacity",
      valueType: "integer",
      unit: "mah",
      normalizer: "quantity",
      group: "battery",
      scoring: { component: "battery", weight: 2, higherIsBetter: true },
    },
    {
      key: "console_battery_life_hours",
      label: "Battery life",
      hint: "Manufacturer-rated handheld playtime. Varies a lot by game — demanding titles drain it faster.",
      valueType: "number",
      unit: "hours",
      normalizer: "quantity",
      group: "battery",
      scoring: { component: "battery", weight: 3, higherIsBetter: true },
    },
    {
      key: "console_charging_w",
      label: "Charging speed",
      valueType: "integer",
      unit: "w",
      normalizer: "quantity",
      group: "battery",
      scoring: { component: "battery", weight: 1, higherIsBetter: true },
    },
    // --- Connectivity ----------------------------------------------
    {
      key: "wifi_gen",
      label: "Wi-Fi",
      valueType: "enum",
      normalizer: "enum",
      enumValues: ["Wi-Fi 4", "Wi-Fi 5", "Wi-Fi 6", "Wi-Fi 6E", "Wi-Fi 7"],
      enumRank: ["Wi-Fi 7", "Wi-Fi 6E", "Wi-Fi 6", "Wi-Fi 5", "Wi-Fi 4"],
      group: "connectivity",
      scoring: { component: "features", weight: 1, higherIsBetter: true },
    },
    {
      key: "bluetooth_version",
      label: "Bluetooth",
      valueType: "enum",
      normalizer: "enum",
      enumValues: ["Bluetooth 4.2", "Bluetooth 5.0", "Bluetooth 5.1", "Bluetooth 5.2", "Bluetooth 5.3"],
      enumRank: ["Bluetooth 5.3", "Bluetooth 5.2", "Bluetooth 5.1", "Bluetooth 5.0", "Bluetooth 4.2"],
      group: "connectivity",
      scoring: { component: "features", weight: 0.5, higherIsBetter: true },
    },
    {
      key: "nfc",
      label: "NFC",
      hint: "Needed for tap-to-scan amiibo/accessory support.",
      valueType: "boolean",
      normalizer: "boolean",
      group: "connectivity",
      scoring: { component: "features", weight: 0.5, higherIsBetter: true },
    },
    {
      key: "console_usb_ports",
      label: "USB-C ports",
      valueType: "integer",
      unit: "count",
      normalizer: "quantity",
      group: "connectivity",
      scoring: { component: "features", weight: 1, higherIsBetter: true },
    },
    {
      key: "game_card_slot",
      label: "Physical game card slot",
      valueType: "boolean",
      normalizer: "boolean",
      group: "connectivity",
      scoring: { component: "features", weight: 1, higherIsBetter: true },
    },
    {
      key: "headphone_jack",
      label: "Headphone jack",
      valueType: "boolean",
      normalizer: "boolean",
      group: "connectivity",
      scoring: { component: "features", weight: 0.5, higherIsBetter: true },
    },
    // --- Build ----------------------------------------------------
    {
      key: "console_weight_g",
      label: "Weight",
      hint: "Handheld weight (as held, e.g. with controllers attached). Lighter is more comfortable for long handheld sessions.",
      valueType: "number",
      unit: "g",
      normalizer: "quantity",
      group: "build",
      scoring: { component: "build", weight: 1.5, higherIsBetter: false },
    },
    {
      key: "form_factor",
      label: "Form factor",
      valueType: "text",
      normalizer: "passthrough",
      group: "build",
    },
    {
      key: "has_dock",
      label: "TV dock included",
      hint: "Whether a dock for TV play ships in the box, versus being sold separately.",
      valueType: "boolean",
      normalizer: "boolean",
      group: "build",
      scoring: { component: "build", weight: 1, higherIsBetter: true },
    },
    // --- Software ------------------------------------------------
    {
      key: "os",
      label: "System software",
      valueType: "text",
      normalizer: "passthrough",
      group: "software",
    },
    {
      key: "firmware_updatable",
      label: "Firmware updates",
      valueType: "boolean",
      normalizer: "boolean",
      group: "software",
      scoring: { component: "software", weight: 1, higherIsBetter: true },
    },
  ],
};
