import type { CategorySchema } from "@/lib/intelligence/types";

/**
 * The laptop category schema. Same role as `smartphone.ts`: the canonical
 * attribute set a laptop `ProductProfile` can hold, how each raw value
 * normalizes, which comparison-UI group it belongs to, and how it feeds a
 * NURU Score component.
 *
 * A handful of attributes deliberately do NOT reuse a same-named smartphone
 * attribute (`ram_gb`, `storage_gb`, `weight_g`, `display_ppi`,
 * `peak_brightness_nits`, `chipset`) even though the concept is the same —
 * they're on a different numeric scale (16-64GB laptop RAM vs. 4-16GB phone
 * RAM; a laptop CPU vs. a phone SoC on the same 0-100 index would be
 * meaningless), and `NUMERIC_BANDS`/`TEXT_LOOKUP_TABLES` are one flat
 * namespace keyed by attribute. See `reference.ts` for the laptop-scale bands
 * and the `LAPTOP_CPU_PERFORMANCE_INDEX` table this schema's `cpu` attribute
 * is scored against. Attributes that genuinely share a scale with the
 * smartphone schema (`refresh_rate_hz`, `wifi_gen`) keep the same key.
 */
export const laptopSchema: CategorySchema = {
  id: "laptop",
  label: "Laptop",
  shopifyProductTypes: ["Laptops"],
  groups: [
    { id: "display", label: "Display" },
    { id: "performance", label: "Performance" },
    { id: "memory", label: "Memory & Storage" },
    { id: "camera", label: "Webcam" },
    { id: "battery", label: "Battery & Charging" },
    { id: "connectivity", label: "Connectivity" },
    { id: "build", label: "Build & Design" },
    { id: "software", label: "Software" },
  ],
  componentWeights: {
    performance: 0.28,
    display: 0.18,
    battery: 0.16,
    build: 0.14,
    features: 0.12,
    camera: 0.05,
    software: 0.04,
    value: 0.03,
  },
  attributes: [
    // --- Display ---------------------------------------------------------
    {
      key: "display_size_in",
      label: "Display size",
      hint: "Screen size corner to corner. Bigger is easier for multitasking and video; smaller is lighter to carry.",
      valueType: "number",
      unit: "in",
      normalizer: "quantity",
      group: "display",
    },
    {
      key: "display_tech",
      label: "Display type",
      hint: "OLED and Mini-LED panels have deeper blacks and better contrast than a standard IPS LCD.",
      valueType: "enum",
      normalizer: "enum",
      enumValues: ["LCD", "IPS LCD", "Mini-LED", "OLED"],
      enumRank: ["OLED", "Mini-LED", "IPS LCD", "LCD"],
      group: "display",
      scoring: { component: "display", weight: 2, higherIsBetter: true },
    },
    {
      key: "display_resolution",
      label: "Resolution",
      hint: "Total pixels. More pixels look sharper, most visibly on larger screens.",
      valueType: "text",
      normalizer: "resolution",
      group: "display",
    },
    {
      key: "laptop_display_ppi",
      label: "Pixel density",
      hint: "Pixels per inch. Laptops sit further from your eyes than phones, so this matters less than it does on a phone, but text still looks crisper above ~220 ppi.",
      valueType: "integer",
      unit: "ppi",
      normalizer: "quantity",
      group: "display",
      scoring: { component: "display", weight: 1.5, higherIsBetter: true },
    },
    {
      key: "refresh_rate_hz",
      label: "Refresh rate",
      hint: "How many times a second the screen redraws. 90/120Hz makes scrolling and animation look smoother than 60Hz.",
      valueType: "integer",
      unit: "hz",
      normalizer: "quantity",
      group: "display",
      scoring: { component: "display", weight: 1.5, higherIsBetter: true },
    },
    {
      key: "laptop_peak_brightness_nits",
      label: "Peak brightness",
      hint: "How bright the screen can get. Higher means more readable outdoors or under office lighting.",
      valueType: "integer",
      unit: "nits",
      normalizer: "quantity",
      group: "display",
      scoring: { component: "display", weight: 1, higherIsBetter: true },
    },
    // --- Performance ------------------------------------------------------
    {
      key: "cpu",
      label: "Processor",
      hint: "The main chip. Faster chips handle video editing, compiling and heavy multitasking without slowing down.",
      valueType: "text",
      normalizer: "chipset",
      group: "performance",
      // Scored via LAPTOP_CPU_PERFORMANCE_INDEX in reference.ts, not a raw number.
      scoring: { component: "performance", weight: 5, higherIsBetter: true },
    },
    {
      key: "cpu_cores",
      label: "CPU cores",
      valueType: "integer",
      unit: "cores",
      normalizer: "quantity",
      group: "performance",
    },
    {
      key: "gpu",
      label: "Graphics",
      hint: "Integrated graphics handle everyday use and light creative work; a discrete GPU is built for gaming and heavy rendering.",
      valueType: "text",
      normalizer: "passthrough",
      group: "performance",
    },
    // --- Memory ------------------------------------------------------
    {
      key: "laptop_ram_gb",
      label: "RAM",
      hint: "Working memory. More RAM keeps more apps, browser tabs and background tasks running smoothly at once.",
      valueType: "integer",
      unit: "gb",
      normalizer: "storage",
      group: "memory",
      scoring: { component: "performance", weight: 2.5, higherIsBetter: true },
    },
    {
      key: "laptop_storage_gb",
      label: "Storage",
      hint: "Space for the OS, apps and files. Most laptops can't have storage added later.",
      valueType: "integer",
      unit: "gb",
      normalizer: "storage",
      group: "memory",
      scoring: { component: "features", weight: 1.5, higherIsBetter: true },
    },
    {
      key: "storage_type",
      label: "Storage type",
      hint: "An SSD is dramatically faster to boot and load from than a spinning HDD.",
      valueType: "enum",
      normalizer: "enum",
      enumValues: ["HDD", "eMMC", "SSD"],
      enumRank: ["SSD", "eMMC", "HDD"],
      group: "memory",
      scoring: { component: "features", weight: 1, higherIsBetter: true },
    },
    {
      key: "expandable_storage",
      label: "User-upgradeable storage/RAM",
      hint: "Whether you can open the case and add more RAM or swap the drive later.",
      valueType: "boolean",
      normalizer: "boolean",
      group: "memory",
      scoring: { component: "features", weight: 0.5, higherIsBetter: true },
    },
    // --- Webcam -------------------------------------------------------
    {
      key: "laptop_webcam_mp",
      label: "Webcam resolution",
      hint: "Sharpness of the built-in camera for video calls.",
      valueType: "integer",
      unit: "mp",
      normalizer: "quantity",
      group: "camera",
      scoring: { component: "camera", weight: 2, higherIsBetter: true },
    },
    {
      key: "webcam_max_video",
      label: "Webcam video quality",
      valueType: "enum",
      normalizer: "enum",
      enumValues: ["720p", "1080p", "4K"],
      enumRank: ["4K", "1080p", "720p"],
      group: "camera",
      scoring: { component: "camera", weight: 1, higherIsBetter: true },
    },
    // --- Battery -----------------------------------------------------
    {
      key: "laptop_battery_wh",
      label: "Battery capacity",
      hint: "Bigger generally means longer between charges, though the screen and chip's efficiency matter too.",
      valueType: "number",
      unit: "wh",
      normalizer: "quantity",
      group: "battery",
      scoring: { component: "battery", weight: 3, higherIsBetter: true },
    },
    {
      key: "battery_life_hours",
      label: "Rated battery life",
      hint: "The manufacturer's own estimate for typical use. Real-world life is usually somewhat lower.",
      valueType: "number",
      unit: "hours",
      normalizer: "quantity",
      group: "battery",
      scoring: { component: "battery", weight: 3, higherIsBetter: true },
    },
    {
      key: "laptop_charging_w",
      label: "Charging speed",
      hint: "Wattage of the charger it ships with. Higher means a faster top-up.",
      valueType: "integer",
      unit: "w",
      normalizer: "quantity",
      group: "battery",
      scoring: { component: "battery", weight: 1, higherIsBetter: true },
    },
    // --- Connectivity --------------------------------------------------
    {
      key: "wifi_gen",
      label: "Wi-Fi",
      valueType: "enum",
      normalizer: "enum",
      enumValues: ["Wi-Fi 4", "Wi-Fi 5", "Wi-Fi 6", "Wi-Fi 6E", "Wi-Fi 7"],
      enumRank: ["Wi-Fi 7", "Wi-Fi 6E", "Wi-Fi 6", "Wi-Fi 5", "Wi-Fi 4"],
      group: "connectivity",
      scoring: { component: "features", weight: 0.5, higherIsBetter: true },
    },
    {
      key: "bluetooth_version",
      label: "Bluetooth",
      valueType: "enum",
      normalizer: "enum",
      enumValues: ["Bluetooth 4.2", "Bluetooth 5.0", "Bluetooth 5.1", "Bluetooth 5.2", "Bluetooth 5.3"],
      enumRank: ["Bluetooth 5.3", "Bluetooth 5.2", "Bluetooth 5.1", "Bluetooth 5.0", "Bluetooth 4.2"],
      group: "connectivity",
      scoring: { component: "features", weight: 0.5, higherIsBetter: true },
    },
    {
      key: "thunderbolt_ports",
      label: "Thunderbolt / USB4 ports",
      hint: "High-speed ports for fast external drives, docks and multiple monitors.",
      valueType: "integer",
      unit: "count",
      normalizer: "quantity",
      group: "connectivity",
      scoring: { component: "features", weight: 1.5, higherIsBetter: true },
    },
    {
      key: "has_hdmi",
      label: "HDMI port",
      valueType: "boolean",
      normalizer: "boolean",
      group: "connectivity",
      scoring: { component: "features", weight: 0.5, higherIsBetter: true },
    },
    {
      key: "has_sd_card_slot",
      label: "SD card slot",
      valueType: "boolean",
      normalizer: "boolean",
      group: "connectivity",
      scoring: { component: "features", weight: 0.5, higherIsBetter: true },
    },
    // --- Build ----------------------------------------------------
    {
      key: "laptop_weight_kg",
      label: "Weight",
      hint: "Lighter is easier to carry daily; heavier often means a bigger battery or more ports.",
      valueType: "number",
      unit: "kg",
      normalizer: "quantity",
      group: "build",
      scoring: { component: "build", weight: 2, higherIsBetter: false },
    },
    {
      key: "build_materials",
      label: "Chassis material",
      hint: "Aluminium and magnesium alloy feel more premium and resist flex better than plastic.",
      valueType: "text",
      normalizer: "passthrough",
      group: "build",
    },
    {
      key: "keyboard_backlit",
      label: "Backlit keyboard",
      valueType: "boolean",
      normalizer: "boolean",
      group: "build",
      scoring: { component: "build", weight: 0.5, higherIsBetter: true },
    },
    {
      key: "biometrics",
      label: "Unlock",
      valueType: "text",
      normalizer: "passthrough",
      group: "build",
    },
    // --- Software ------------------------------------------------
    {
      key: "os",
      label: "Operating system",
      valueType: "text",
      normalizer: "passthrough",
      group: "software",
    },
    {
      key: "laptop_os_update_years",
      label: "OS update commitment",
      hint: "How many years of major OS upgrades the maker has promised. Longer means the laptop stays current and secure for longer.",
      valueType: "integer",
      unit: "years",
      normalizer: "quantity",
      group: "software",
      scoring: { component: "software", weight: 3, higherIsBetter: true },
    },
  ],
};
