import type { CategorySchema } from "@/lib/intelligence/types";

/**
 * The smartphone category schema.
 *
 * This is the canonical attribute set for phones: what a `ProductProfile` in
 * the "smartphone" category can hold, how each raw value is normalized, which
 * comparison-UI group it belongs to, and (where applicable) how it feeds a NURU
 * Score component. It is code, not data — adding an attribute or re-tuning a
 * weight is a reviewed change, and the scoring engine reads its numbers rather
 * than carrying its own.
 *
 * `hint` text is buyer-facing: it appears in the comparison UI and the spec
 * glossary, so it explains what the number means for a shopper, not what it is.
 *
 * Attributes with no `scoring` block are identity or descriptive fields — shown
 * in comparisons, never rolled into a score.
 */
export const smartphoneSchema: CategorySchema = {
  id: "smartphone",
  label: "Smartphone",
  shopifyProductTypes: ["Smartphones"],
  groups: [
    { id: "display", label: "Display" },
    { id: "performance", label: "Performance" },
    { id: "memory", label: "Memory & Storage" },
    { id: "camera", label: "Camera" },
    { id: "battery", label: "Battery & Charging" },
    { id: "connectivity", label: "Connectivity" },
    { id: "build", label: "Build & Design" },
    { id: "software", label: "Software" },
  ],
  componentWeights: {
    performance: 0.18,
    camera: 0.2,
    battery: 0.18,
    display: 0.15,
    build: 0.1,
    features: 0.08,
    software: 0.07,
    value: 0.04,
  },
  attributes: [
    // --- Display ---------------------------------------------------------
    {
      key: "display_size_in",
      label: "Display size",
      hint: "Screen size corner to corner. Bigger is easier for video and reading; smaller is easier one-handed.",
      valueType: "number",
      unit: "in",
      normalizer: "quantity",
      group: "display",
    },
    {
      key: "display_tech",
      label: "Display type",
      hint: "OLED/AMOLED panels have deeper blacks and better contrast than LCD, and usually better outdoor visibility.",
      valueType: "enum",
      normalizer: "enum",
      enumValues: ["LCD", "IPS LCD", "OLED", "AMOLED", "LTPO OLED"],
      enumRank: ["LTPO OLED", "AMOLED", "OLED", "IPS LCD", "LCD"],
      group: "display",
      scoring: { component: "display", weight: 2, higherIsBetter: true },
    },
    {
      key: "display_resolution",
      label: "Resolution",
      hint: "Total pixels. More pixels look sharper, most visibly on larger screens.",
      valueType: "text",
      normalizer: "resolution",
      group: "display",
    },
    {
      key: "display_ppi",
      label: "Pixel density",
      hint: "Pixels per inch. Above ~400 ppi individual pixels are invisible at normal distance.",
      valueType: "integer",
      unit: "ppi",
      normalizer: "quantity",
      group: "display",
      scoring: { component: "display", weight: 1.5, higherIsBetter: true },
    },
    {
      key: "refresh_rate_hz",
      label: "Refresh rate",
      hint: "How many times a second the screen redraws. 90/120Hz makes scrolling and animation look smoother than 60Hz.",
      valueType: "integer",
      unit: "hz",
      normalizer: "quantity",
      group: "display",
      scoring: { component: "display", weight: 2.5, higherIsBetter: true },
    },
    {
      key: "peak_brightness_nits",
      label: "Peak brightness",
      hint: "How bright the screen can get. Higher means more readable in direct sunlight.",
      valueType: "integer",
      unit: "nits",
      normalizer: "quantity",
      group: "display",
      scoring: { component: "display", weight: 2, higherIsBetter: true },
    },
    // --- Performance ----------------------------------------------------
    {
      key: "chipset",
      label: "Processor",
      hint: "The main chip. Faster chips handle demanding games and long recording sessions without slowing down.",
      valueType: "text",
      normalizer: "chipset",
      group: "performance",
      // Scored via the chip→performance-index table in the scoring engine, not a raw number.
      scoring: { component: "performance", weight: 5, higherIsBetter: true },
    },
    {
      key: "cpu_cores",
      label: "CPU cores",
      valueType: "integer",
      unit: "cores",
      normalizer: "quantity",
      group: "performance",
    },
    {
      key: "gpu",
      label: "Graphics",
      valueType: "text",
      normalizer: "passthrough",
      group: "performance",
    },
    // --- Memory --------------------------------------------------------
    {
      key: "ram_gb",
      label: "RAM",
      hint: "Working memory. More RAM keeps more apps open in the background without reloading.",
      valueType: "integer",
      unit: "gb",
      normalizer: "storage",
      group: "memory",
      scoring: { component: "performance", weight: 2, higherIsBetter: true },
    },
    {
      key: "storage_gb",
      label: "Storage",
      hint: "Space for apps, photos and video. Can't be increased later unless the phone takes a memory card.",
      valueType: "integer",
      unit: "gb",
      normalizer: "storage",
      group: "memory",
      scoring: { component: "features", weight: 1.5, higherIsBetter: true },
    },
    {
      key: "expandable_storage",
      label: "Memory card slot",
      hint: "Whether you can add storage with a microSD card.",
      valueType: "boolean",
      normalizer: "boolean",
      group: "memory",
      scoring: { component: "features", weight: 0.5, higherIsBetter: true },
    },
    // --- Camera -------------------------------------------------------
    {
      key: "main_cam_mp",
      label: "Main camera",
      hint: "Resolution of the primary rear camera. Sensor size and processing matter as much as the megapixel number.",
      valueType: "integer",
      unit: "mp",
      normalizer: "quantity",
      group: "camera",
      scoring: { component: "camera", weight: 3, higherIsBetter: true },
    },
    {
      key: "main_cam_ois",
      label: "Main camera stabilisation (OIS)",
      hint: "Optical image stabilisation. Sharper low-light photos and steadier video.",
      valueType: "boolean",
      normalizer: "boolean",
      group: "camera",
      scoring: { component: "camera", weight: 1.5, higherIsBetter: true },
    },
    {
      key: "ultrawide_mp",
      label: "Ultrawide camera",
      hint: "A second wider lens for landscapes and group shots. Absent on many budget phones.",
      valueType: "integer",
      unit: "mp",
      normalizer: "quantity",
      group: "camera",
      scoring: { component: "camera", weight: 1.5, higherIsBetter: true },
    },
    {
      key: "telephoto_mp",
      label: "Telephoto camera",
      hint: "A dedicated zoom lens. Keeps detail when zoomed in, unlike digital crop.",
      valueType: "integer",
      unit: "mp",
      normalizer: "quantity",
      group: "camera",
      scoring: { component: "camera", weight: 2, higherIsBetter: true },
    },
    {
      key: "telephoto_zoom_x",
      label: "Optical zoom",
      valueType: "number",
      unit: "x",
      normalizer: "quantity",
      group: "camera",
      scoring: { component: "camera", weight: 1, higherIsBetter: true },
    },
    {
      key: "front_cam_mp",
      label: "Front camera",
      valueType: "integer",
      unit: "mp",
      normalizer: "quantity",
      group: "camera",
      scoring: { component: "camera", weight: 1, higherIsBetter: true },
    },
    {
      key: "video_max_resolution",
      label: "Max video resolution",
      hint: "The highest-quality video the phone records. 4K is plenty for most; 8K needs a lot of storage.",
      valueType: "enum",
      normalizer: "enum",
      enumValues: ["1080p", "4K", "8K"],
      enumRank: ["8K", "4K", "1080p"],
      group: "camera",
      scoring: { component: "camera", weight: 1, higherIsBetter: true },
    },
    // --- Battery -----------------------------------------------------
    {
      key: "battery_mah",
      label: "Battery capacity",
      hint: "Bigger generally means longer between charges, though screen size and chip efficiency also matter.",
      valueType: "integer",
      unit: "mah",
      normalizer: "quantity",
      group: "battery",
      scoring: { component: "battery", weight: 4, higherIsBetter: true },
    },
    {
      key: "charging_wired_w",
      label: "Wired charging",
      hint: "Charging speed with a cable. Higher wattage fills the battery faster.",
      valueType: "integer",
      unit: "w",
      normalizer: "quantity",
      group: "battery",
      scoring: { component: "battery", weight: 2, higherIsBetter: true },
    },
    {
      key: "charging_wireless_w",
      label: "Wireless charging",
      valueType: "integer",
      unit: "w",
      normalizer: "quantity",
      group: "battery",
      scoring: { component: "battery", weight: 1, higherIsBetter: true },
    },
    {
      key: "reverse_charging",
      label: "Reverse wireless charging",
      hint: "Whether the phone can top up earbuds or another phone from its own battery.",
      valueType: "boolean",
      normalizer: "boolean",
      group: "battery",
      scoring: { component: "features", weight: 0.5, higherIsBetter: true },
    },
    // --- Connectivity ----------------------------------------------
    {
      key: "cellular",
      label: "Mobile network",
      valueType: "enum",
      normalizer: "enum",
      enumValues: ["3G", "4G", "5G"],
      enumRank: ["5G", "4G", "3G"],
      group: "connectivity",
      scoring: { component: "features", weight: 1.5, higherIsBetter: true },
    },
    {
      key: "wifi_gen",
      label: "Wi-Fi",
      valueType: "enum",
      normalizer: "enum",
      enumValues: ["Wi-Fi 4", "Wi-Fi 5", "Wi-Fi 6", "Wi-Fi 6E", "Wi-Fi 7"],
      enumRank: ["Wi-Fi 7", "Wi-Fi 6E", "Wi-Fi 6", "Wi-Fi 5", "Wi-Fi 4"],
      group: "connectivity",
      scoring: { component: "features", weight: 0.5, higherIsBetter: true },
    },
    {
      key: "nfc",
      label: "NFC",
      hint: "Needed for tap-to-pay and quick pairing.",
      valueType: "boolean",
      normalizer: "boolean",
      group: "connectivity",
      scoring: { component: "features", weight: 0.75, higherIsBetter: true },
    },
    {
      key: "usb_standard",
      label: "Charging port",
      valueType: "enum",
      normalizer: "enum",
      enumValues: ["Micro-USB", "USB-C", "Lightning", "USB 2.0", "USB 3.0", "USB 3.2"],
      group: "connectivity",
    },
    {
      key: "sim_config",
      label: "SIM",
      valueType: "text",
      normalizer: "passthrough",
      group: "connectivity",
    },
    // --- Build ----------------------------------------------------
    {
      key: "ip_rating",
      label: "Water resistance",
      hint: "IP rating for dust and water. IP68 tolerates brief submersion; no rating means keep it dry.",
      valueType: "enum",
      normalizer: "enum",
      enumValues: ["None", "IP52", "IP53", "IP54", "IP67", "IP68", "IP69"],
      enumRank: ["IP69", "IP68", "IP67", "IP54", "IP53", "IP52", "None"],
      group: "build",
      scoring: { component: "build", weight: 2, higherIsBetter: true },
    },
    {
      key: "weight_g",
      label: "Weight",
      hint: "Lighter is easier to hold for long periods; heavier often means a bigger battery or glass/metal build.",
      valueType: "number",
      unit: "g",
      normalizer: "quantity",
      group: "build",
      scoring: { component: "build", weight: 1, higherIsBetter: false },
    },
    {
      key: "build_materials",
      label: "Frame & back",
      hint: "Glass and metal feel more premium and can survive drops differently than plastic.",
      valueType: "text",
      normalizer: "passthrough",
      group: "build",
    },
    {
      key: "biometrics",
      label: "Unlock",
      valueType: "text",
      normalizer: "passthrough",
      group: "build",
    },
    // --- Software ------------------------------------------------
    {
      key: "os",
      label: "Operating system",
      valueType: "text",
      normalizer: "passthrough",
      group: "software",
    },
    {
      key: "android_version",
      label: "Android/iOS version at launch",
      valueType: "number",
      normalizer: "quantity",
      group: "software",
    },
    {
      key: "os_update_years",
      label: "OS update commitment",
      hint: "How many years of major OS upgrades the maker has promised. Longer means the phone stays current and secure for longer.",
      valueType: "integer",
      unit: "years",
      normalizer: "quantity",
      group: "software",
      scoring: { component: "software", weight: 3, higherIsBetter: true },
    },
    {
      key: "security_update_years",
      label: "Security update commitment",
      valueType: "integer",
      unit: "years",
      normalizer: "quantity",
      group: "software",
      scoring: { component: "software", weight: 2, higherIsBetter: true },
    },
  ],
};
