import type { CategorySchema } from "@/lib/intelligence/types";

/**
 * The tablet category schema. Same role as `smartphone.ts` / `laptop.ts`.
 *
 * The `cpu` attribute deliberately shares its key and `LAPTOP_CPU_PERFORMANCE_INDEX`
 * lookup table with the laptop schema — a tablet built on real laptop-class
 * silicon (an iPad's Apple M-series chip) genuinely performs on that same
 * scale, unlike a phone SoC. Every other scored numeric attribute here gets
 * its own `tablet_*` key/band in `reference.ts`: a tablet's RAM, battery,
 * camera and weight ranges don't match either a phone's or a laptop's, and
 * NUMERIC_BANDS is one flat namespace keyed by attribute — reusing a phone or
 * laptop key would silently score a tablet against the wrong yardstick.
 */
export const tabletSchema: CategorySchema = {
  id: "tablet",
  label: "Tablet",
  shopifyProductTypes: ["Tablets"],
  groups: [
    { id: "display", label: "Display" },
    { id: "performance", label: "Performance" },
    { id: "memory", label: "Memory & Storage" },
    { id: "camera", label: "Camera" },
    { id: "battery", label: "Battery & Charging" },
    { id: "connectivity", label: "Connectivity" },
    { id: "build", label: "Build & Design" },
    { id: "software", label: "Software" },
  ],
  componentWeights: {
    performance: 0.22,
    display: 0.2,
    battery: 0.16,
    features: 0.12,
    build: 0.12,
    camera: 0.1,
    software: 0.05,
    value: 0.03,
  },
  attributes: [
    // --- Display ---------------------------------------------------------
    {
      key: "display_size_in",
      label: "Display size",
      hint: "Screen size corner to corner. Bigger is better for reading, drawing and video; smaller is lighter to hold one-handed.",
      valueType: "number",
      unit: "in",
      normalizer: "quantity",
      group: "display",
    },
    {
      key: "display_tech",
      label: "Display type",
      hint: "OLED panels have deeper blacks and better contrast than LCD.",
      valueType: "enum",
      normalizer: "enum",
      enumValues: ["LCD", "IPS LCD", "Mini-LED", "OLED"],
      enumRank: ["OLED", "Mini-LED", "IPS LCD", "LCD"],
      group: "display",
      scoring: { component: "display", weight: 2, higherIsBetter: true },
    },
    {
      key: "display_resolution",
      label: "Resolution",
      hint: "Total pixels. More pixels look sharper, most visibly for text and fine detail.",
      valueType: "text",
      normalizer: "resolution",
      group: "display",
    },
    {
      key: "tablet_display_ppi",
      label: "Pixel density",
      hint: "Pixels per inch. Above ~260 ppi individual pixels are essentially invisible at normal reading distance.",
      valueType: "integer",
      unit: "ppi",
      normalizer: "quantity",
      group: "display",
      scoring: { component: "display", weight: 1.5, higherIsBetter: true },
    },
    {
      key: "refresh_rate_hz",
      label: "Refresh rate",
      hint: "How many times a second the screen redraws. 90/120Hz makes scrolling and drawing with a stylus feel smoother than 60Hz.",
      valueType: "integer",
      unit: "hz",
      normalizer: "quantity",
      group: "display",
      scoring: { component: "display", weight: 1.5, higherIsBetter: true },
    },
    {
      key: "tablet_peak_brightness_nits",
      label: "Peak brightness",
      hint: "How bright the screen can get. Higher means more readable outdoors.",
      valueType: "integer",
      unit: "nits",
      normalizer: "quantity",
      group: "display",
      scoring: { component: "display", weight: 1, higherIsBetter: true },
    },
    // --- Performance ------------------------------------------------------
    {
      key: "cpu",
      label: "Processor",
      hint: "The main chip. Faster chips handle demanding apps, multitasking and photo/video editing without slowing down.",
      valueType: "text",
      normalizer: "chipset",
      group: "performance",
      // Scored via LAPTOP_CPU_PERFORMANCE_INDEX in reference.ts — see module doc.
      scoring: { component: "performance", weight: 5, higherIsBetter: true },
    },
    {
      key: "gpu",
      label: "Graphics",
      valueType: "text",
      normalizer: "passthrough",
      group: "performance",
    },
    // --- Memory --------------------------------------------------------
    {
      key: "tablet_ram_gb",
      label: "RAM",
      hint: "Working memory. More RAM keeps more apps and browser tabs open in the background without reloading.",
      valueType: "integer",
      unit: "gb",
      normalizer: "storage",
      group: "memory",
      scoring: { component: "performance", weight: 2, higherIsBetter: true },
    },
    {
      key: "tablet_storage_gb",
      label: "Storage",
      hint: "Space for apps, files and downloaded media. Can't be increased later unless the tablet takes a memory card.",
      valueType: "integer",
      unit: "gb",
      normalizer: "storage",
      group: "memory",
      scoring: { component: "features", weight: 1.5, higherIsBetter: true },
    },
    {
      key: "expandable_storage",
      label: "Memory card slot",
      hint: "Whether you can add storage with a microSD card.",
      valueType: "boolean",
      normalizer: "boolean",
      group: "memory",
      scoring: { component: "features", weight: 0.5, higherIsBetter: true },
    },
    // --- Camera -------------------------------------------------------
    {
      key: "tablet_main_cam_mp",
      label: "Rear camera",
      hint: "Resolution of the rear camera. Most tablets prioritise the front camera for video calls over the rear one for photos.",
      valueType: "integer",
      unit: "mp",
      normalizer: "quantity",
      group: "camera",
      scoring: { component: "camera", weight: 2, higherIsBetter: true },
    },
    {
      key: "tablet_front_cam_mp",
      label: "Front camera",
      hint: "Resolution of the front camera used for video calls.",
      valueType: "integer",
      unit: "mp",
      normalizer: "quantity",
      group: "camera",
      scoring: { component: "camera", weight: 2, higherIsBetter: true },
    },
    {
      key: "video_max_resolution",
      label: "Max video resolution",
      valueType: "enum",
      normalizer: "enum",
      enumValues: ["1080p", "4K", "8K"],
      enumRank: ["8K", "4K", "1080p"],
      group: "camera",
      scoring: { component: "camera", weight: 1, higherIsBetter: true },
    },
    // --- Battery -----------------------------------------------------
    {
      key: "tablet_battery_wh",
      label: "Battery capacity",
      hint: "Bigger generally means longer between charges, though screen size and chip efficiency also matter.",
      valueType: "number",
      unit: "wh",
      normalizer: "quantity",
      group: "battery",
      scoring: { component: "battery", weight: 4, higherIsBetter: true },
    },
    {
      key: "tablet_charging_w",
      label: "Charging speed",
      hint: "Wattage of the charger it ships with. Higher means a faster top-up.",
      valueType: "integer",
      unit: "w",
      normalizer: "quantity",
      group: "battery",
      scoring: { component: "battery", weight: 2, higherIsBetter: true },
    },
    // --- Connectivity ----------------------------------------------
    {
      key: "cellular",
      label: "Mobile network",
      hint: "Whether a cellular variant exists, so the tablet can get online without Wi-Fi.",
      valueType: "enum",
      normalizer: "enum",
      enumValues: ["None", "4G", "5G"],
      enumRank: ["5G", "4G", "None"],
      group: "connectivity",
      scoring: { component: "features", weight: 1, higherIsBetter: true },
    },
    {
      key: "wifi_gen",
      label: "Wi-Fi",
      valueType: "enum",
      normalizer: "enum",
      enumValues: ["Wi-Fi 4", "Wi-Fi 5", "Wi-Fi 6", "Wi-Fi 6E", "Wi-Fi 7"],
      enumRank: ["Wi-Fi 7", "Wi-Fi 6E", "Wi-Fi 6", "Wi-Fi 5", "Wi-Fi 4"],
      group: "connectivity",
      scoring: { component: "features", weight: 0.75, higherIsBetter: true },
    },
    {
      key: "usb_standard",
      label: "Charging port",
      valueType: "enum",
      normalizer: "enum",
      enumValues: ["Micro-USB", "USB-C", "Lightning", "USB 2.0", "USB 3.0", "USB 3.2"],
      group: "connectivity",
    },
    {
      key: "stylus_support",
      label: "Stylus support",
      hint: "Whether the tablet supports a pressure-sensitive pen for drawing and notes.",
      valueType: "boolean",
      normalizer: "boolean",
      group: "connectivity",
      scoring: { component: "features", weight: 1, higherIsBetter: true },
    },
    // --- Build ----------------------------------------------------
    {
      key: "tablet_weight_g",
      label: "Weight",
      hint: "Lighter is easier to hold for long reading or drawing sessions; heavier often means a bigger battery.",
      valueType: "number",
      unit: "g",
      normalizer: "quantity",
      group: "build",
      scoring: { component: "build", weight: 1.5, higherIsBetter: false },
    },
    {
      key: "build_materials",
      label: "Frame & back",
      valueType: "text",
      normalizer: "passthrough",
      group: "build",
    },
    {
      key: "biometrics",
      label: "Unlock",
      valueType: "text",
      normalizer: "passthrough",
      group: "build",
    },
    // --- Software ------------------------------------------------
    {
      key: "os",
      label: "Operating system",
      valueType: "text",
      normalizer: "passthrough",
      group: "software",
    },
    {
      key: "os_update_years",
      label: "OS update commitment",
      hint: "How many years of major OS upgrades the maker has promised. Longer means the tablet stays current and secure for longer.",
      valueType: "integer",
      unit: "years",
      normalizer: "quantity",
      group: "software",
      scoring: { component: "software", weight: 3, higherIsBetter: true },
    },
  ],
};
