import "server-only";
import { prisma } from "../prisma";
import { formatPrice } from "../format";
import {
  BANKROLL_USD,
  CAPITAL_CIRCLE_LIVE,
  DEFAULT_PER_POSITION_CAP_USD,
  MAX_CONSECUTIVE_LOSSES,
  MAX_OPEN_POSITIONS,
  MAX_TOTAL_EXPOSURE_USD,
  MAX_WEEKLY_DRAWDOWN_USD,
} from "./config";
import { applyCaps, kellySize, type CapWindow } from "./trade-policy";
import { weekStartOf } from "./sweep";
import { getSimulatedAccountState } from "./track-record";

export type SizingResult = {
  approvedUsd: number;
  capUsd: number;
  capped: boolean;
  reason: string;
  /** The raw Kelly fraction behind the recommendation, persisted on the position for later analysis. */
  kellyFraction: number | null;
};

export type SizingInput = {
  /** A ceiling the caller wants respected. Omitted means Kelly and the caps decide alone. */
  requestedUsd?: number;
  /** Post-shrinkage probability for the outcome being bought. When present, Kelly sizes the position. */
  shrunkProbability?: number;
  /** Ask-side entry price the trade would pay. */
  effectiveEntry?: number;
  /** Resting USD depth on the ask, so the order never becomes the whole book. */
  bookDepthUsd?: number | null;
};

function dayStartOf(date: Date): Date {
  return new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()));
}

function monthStartOf(date: Date): Date {
  return new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), 1));
}

/**
 * Which position statuses count against a velocity cap.
 *
 * Real capital only moves on `executed`, so once live that's the honest
 * measure. But in the current simulation phase nothing is ever `executed`,
 * which meant the velocity caps bound nothing at all and the simulated track
 * record was generated by a strategy with no volume discipline — not a useful
 * predictor of the live one. While simulating, simulated positions count.
 */
function countedStatuses(): ("executed" | "simulated")[] {
  return CAPITAL_CIRCLE_LIVE ? ["executed"] : ["executed", "simulated"];
}

/**
 * Capital already committed since `since`, scoped to one wallet. Scoping by
 * walletId matters: without it, a rotated-out wallet's historical spend would
 * still count against a newly-registered wallet's fresh caps, since Postgres
 * has no concept of "this wallet's cap period starts now." `walletId: null`
 * (no wallet registered at all) intentionally sums unscoped positions rather
 * than matching nothing, so caps still bind before any wallet exists.
 */
async function committedUsdSince(since: Date, walletId: string | null): Promise<number> {
  const result = await prisma.capitalCirclePosition.aggregate({
    where: { status: { in: countedStatuses() }, createdAt: { gte: since }, walletId },
    _sum: { sizeUsd: true },
  });
  return Number(result._sum.sizeUsd ?? 0);
}

export type CircuitBreakerState = { tripped: boolean; reason: string | null };

/**
 * Stops trading after a bad enough run.
 *
 * A drawdown is either variance or a thesis generator that has started
 * producing garbage, and no amount of code can tell those apart from inside.
 * Rather than guess, the pool stops and waits for a human — the asymmetry is
 * that a paused week costs a few missed trades, while an unnoticed broken
 * agent compounds losses every hour, forever.
 */
export async function checkCircuitBreaker(): Promise<CircuitBreakerState> {
  const weekAgo = new Date(Date.now() - 7 * 24 * 3_600_000);
  const [weekly, recent] = await Promise.all([
    prisma.capitalCirclePosition.aggregate({
      where: { resolvedAt: { gte: weekAgo }, status: { in: ["simulated", "executed", "exited"] } },
      _sum: { resultUsd: true },
    }),
    prisma.capitalCirclePosition.findMany({
      where: { resolvedAt: { not: null }, status: { in: ["simulated", "executed", "exited"] } },
      orderBy: { resolvedAt: "desc" },
      take: MAX_CONSECUTIVE_LOSSES,
      select: { resultUsd: true },
    }),
  ]);

  const weeklyPnl = Number(weekly._sum.resultUsd ?? 0);
  if (weeklyPnl < -MAX_WEEKLY_DRAWDOWN_USD) {
    return {
      tripped: true,
      reason: `Trailing-week P&L is ${formatPrice(String(weeklyPnl), "USD")}, past the ${formatPrice(String(MAX_WEEKLY_DRAWDOWN_USD), "USD")} drawdown limit.`,
    };
  }

  if (recent.length >= MAX_CONSECUTIVE_LOSSES && recent.every((position) => Number(position.resultUsd ?? 0) < 0)) {
    return {
      tripped: true,
      reason: `The last ${MAX_CONSECUTIVE_LOSSES} resolved positions all lost — pausing until a human has looked at why.`,
    };
  }

  return { tripped: false, reason: null };
}

/**
 * Risk/Sizing, made literal: decide how much this trade is worth, then bound
 * it by every limit that applies.
 *
 * The size now starts from fractional Kelly on the trade's own edge rather
 * than from whatever number the model asked for — previously `requestedUsd`
 * was the primary input and the caps only ever shrank it, so a model that
 * always requested the cap always received the cap regardless of how thin its
 * edge was. Caps remain the outer bound, never the target.
 */
export async function sizePosition(input: SizingInput | number): Promise<SizingResult> {
  const normalized: SizingInput = typeof input === "number" ? { requestedUsd: input } : input;

  const wallet = await prisma.capitalCircleWallet.findFirst({
    where: { status: "active" },
    orderBy: { createdAt: "desc" },
  });

  const perTxCapUsd = wallet?.perTxCapUsd != null ? Number(wallet.perTxCapUsd) : DEFAULT_PER_POSITION_CAP_USD;
  const reject = (reason: string): SizingResult => ({ approvedUsd: 0, capUsd: perTxCapUsd, capped: true, reason, kellyFraction: null });

  // No stated ceiling means "size this on its merits" — the per-position cap is the outer
  // bound in that case, and Kelly decides everything below it.
  const requestedUsd = normalized.requestedUsd ?? perTxCapUsd;

  if (!Number.isFinite(requestedUsd) || requestedUsd <= 0) {
    return { approvedUsd: 0, capUsd: perTxCapUsd, capped: false, reason: "Requested size was zero or negative.", kellyFraction: null };
  }

  if (wallet?.pausedAt) {
    return reject(`Capital Circle is paused: ${wallet.pausedReason ?? "no reason recorded"}. Clear it from the admin report to resume.`);
  }

  const breaker = await checkCircuitBreaker();
  if (breaker.tripped) {
    if (wallet) {
      await prisma.capitalCircleWallet
        .update({ where: { id: wallet.id }, data: { pausedAt: new Date(), pausedReason: breaker.reason } })
        .catch((error) => console.error("[capital-circle] failed to persist circuit-breaker pause:", error));
    }
    return reject(`Circuit breaker tripped — ${breaker.reason}`);
  }

  // While simulating, the desk is judged as if it actually held BANKROLL_USD — Kelly sizes
  // against the account's current balance below, and this is the "out of money" stop that mirrors
  // what would happen if it were real: once realized losses wipe out the starting budget, no new
  // position can be opened, full stop, regardless of how good the next trade's edge looks. Skipped
  // once live, since a funded wallet balance is the real constraint at that point (see Phase B).
  const account = CAPITAL_CIRCLE_LIVE ? null : await getSimulatedAccountState(BANKROLL_USD);
  if (account?.exhausted) {
    return reject(
      `Simulated budget exhausted: started at ${formatPrice(String(account.startingBudgetUsd), "USD")}, ` +
        `currently ${formatPrice(String(account.currentBalanceUsd), "USD")} after ${account.resolvedCount} resolved positions. ` +
        `No new positions until a human reviews the run.`,
    );
  }

  // Portfolio limits, which had no equivalent before: only a per-position cap existed, so
  // nothing bounded the number of concurrent bets or the pool's total exposure.
  const [openCount, openExposure] = await Promise.all([
    prisma.capitalCirclePosition.count({ where: { resolvedAt: null, status: { in: ["simulated", "executed"] } } }),
    prisma.capitalCirclePosition.aggregate({
      where: { resolvedAt: null, status: { in: ["simulated", "executed"] } },
      _sum: { sizeUsd: true },
    }),
  ]);

  if (openCount >= MAX_OPEN_POSITIONS) {
    return reject(`Already holding ${openCount} open positions, at the limit of ${MAX_OPEN_POSITIONS}.`);
  }

  const exposureUsd = Number(openExposure._sum.sizeUsd ?? 0);
  const exposureHeadroom = Math.max(0, MAX_TOTAL_EXPOSURE_USD - exposureUsd);
  if (exposureHeadroom <= 0) {
    return reject(`Open exposure of ${formatPrice(String(exposureUsd), "USD")} is at the ${formatPrice(String(MAX_TOTAL_EXPOSURE_USD), "USD")} portfolio limit.`);
  }

  // Kelly, when the caller supplied the edge inputs to compute it from.
  let targetUsd = requestedUsd;
  let kellyFraction: number | null = null;
  let kellyNote = "";
  if (normalized.shrunkProbability != null && normalized.effectiveEntry != null) {
    const kelly = kellySize({
      shrunkProbability: normalized.shrunkProbability,
      effectiveEntry: normalized.effectiveEntry,
      capUsd: perTxCapUsd,
      // The account's actual current balance while simulating, so stakes shrink and grow with
      // real performance instead of sizing against a number that never moves — the same way a
      // real trader manages a real, depleting-or-compounding pool of money.
      bankrollUsd: account?.currentBalanceUsd ?? BANKROLL_USD,
      bookDepthUsd: normalized.bookDepthUsd,
    });
    kellyFraction = kelly.kellyFraction;
    if (kelly.recommendedUsd <= 0) {
      return { approvedUsd: 0, capUsd: perTxCapUsd, capped: true, reason: `No Kelly stake: ${kelly.reason}`, kellyFraction };
    }
    targetUsd = Math.min(requestedUsd, kelly.recommendedUsd);
    kellyNote = ` Kelly sizing suggested ${formatPrice(String(kelly.recommendedUsd), "USD")} (${kelly.reason})`;
  }

  const now = new Date();
  const windows: CapWindow[] = [
    { label: "daily", capUsd: wallet?.dailyCapUsd != null ? Number(wallet.dailyCapUsd) : null, spentUsd: 0 },
    { label: "weekly", capUsd: wallet?.weeklyCapUsd != null ? Number(wallet.weeklyCapUsd) : null, spentUsd: 0 },
    { label: "monthly", capUsd: wallet?.monthlyCapUsd != null ? Number(wallet.monthlyCapUsd) : null, spentUsd: 0 },
  ];
  const sinceByLabel: Record<string, Date> = { daily: dayStartOf(now), weekly: weekStartOf(now), monthly: monthStartOf(now) };
  for (const window of windows) {
    if (window.capUsd == null) continue;
    window.spentUsd = await committedUsdSince(sinceByLabel[window.label], wallet?.id ?? null);
  }
  windows.push({ label: "portfolio-exposure", capUsd: MAX_TOTAL_EXPOSURE_USD, spentUsd: exposureUsd });

  const capped = applyCaps({ requestedUsd: targetUsd, perTxCapUsd, windows });

  if (capped.reason) {
    return {
      approvedUsd: capped.approvedUsd,
      capUsd: capped.capUsd,
      capped: true,
      reason: `Requested ${formatPrice(String(requestedUsd), "USD")}:${kellyNote ? `${kellyNote};` : ""} ${capped.reason} — sized down to ${formatPrice(String(capped.approvedUsd), "USD")}.`,
      kellyFraction,
    };
  }

  return {
    approvedUsd: capped.approvedUsd,
    capUsd: capped.capUsd,
    capped: false,
    reason: `Approved ${formatPrice(String(capped.approvedUsd), "USD")} — within all configured caps.${kellyNote}`,
    kellyFraction,
  };
}
