/**
 * Curated, hand-verified smartphone specs — the "NURU spec sheet".
 *
 * This is data NURU stands behind (written at `nuru_csv` / verified
 * confidence), compiled once for the flagship models so the comparison engine
 * has real numbers to work with immediately rather than waiting on the
 * grounded-search crawl. The Gemini pass still fills everything not covered
 * here and can be corrected against this later.
 *
 * Specs are keyed by the smartphone category-schema attribute keys and written
 * as natural strings — the normalization engine reads them. A blank / omitted
 * key means "not seeded", not "none".
 *
 * Current scope: Apple's iPhone line (the store's deepest catalog), including
 * the older models sold as Ex-UK units — an Ex-UK iPhone 13 Pro is a genuine
 * iPhone 13 Pro, so it carries the same model specs.
 */

export type SeedSpecs = Record<string, string>;

/** Specs shared by every iPhone unless a model overrides them. */
const IPHONE_COMMON: SeedSpecs = {
  os: "iOS",
  expandable_storage: "No",
  nfc: "Yes",
  reverse_charging: "No",
  biometrics: "Face ID",
  video_max_resolution: "4K",
  build_materials: "Glass back, aluminium or steel frame",
};

/** model name -> specs. */
export const IPHONE_MODEL_SPECS: Record<string, SeedSpecs> = {
  "iPhone 17 Pro Max": {
    ...IPHONE_COMMON,
    display_size_in: "6.9 in",
    display_tech: "LTPO OLED",
    display_resolution: "2868 x 1320",
    display_ppi: "460",
    refresh_rate_hz: "120 Hz",
    peak_brightness_nits: "3000 nits",
    chipset: "Apple A19 Pro",
    cpu_cores: "6",
    gpu: "Apple 6-core GPU",
    ram_gb: "12 GB",
    storage_gb: "256 GB",
    main_cam_mp: "48 MP",
    main_cam_ois: "Yes",
    ultrawide_mp: "48 MP",
    telephoto_mp: "48 MP",
    telephoto_zoom_x: "8x",
    front_cam_mp: "18 MP",
    battery_mah: "5088 mAh",
    charging_wired_w: "40 W",
    charging_wireless_w: "25 W",
    cellular: "5G",
    wifi_gen: "Wi-Fi 7",
    usb_standard: "USB-C",
    sim_config: "Nano-SIM + eSIM",
    ip_rating: "IP68",
    weight_g: "233 g",
    build_materials: "Aluminium unibody, Ceramic Shield 2",
    android_version: "26",
    os_update_years: "7",
    security_update_years: "7",
  },
  "iPhone 17 Pro": {
    ...IPHONE_COMMON,
    display_size_in: "6.3 in",
    display_tech: "LTPO OLED",
    display_resolution: "2622 x 1206",
    display_ppi: "460",
    refresh_rate_hz: "120 Hz",
    peak_brightness_nits: "3000 nits",
    chipset: "Apple A19 Pro",
    cpu_cores: "6",
    gpu: "Apple 6-core GPU",
    ram_gb: "12 GB",
    storage_gb: "256 GB",
    main_cam_mp: "48 MP",
    main_cam_ois: "Yes",
    ultrawide_mp: "48 MP",
    telephoto_mp: "48 MP",
    telephoto_zoom_x: "8x",
    front_cam_mp: "18 MP",
    battery_mah: "4252 mAh",
    charging_wired_w: "40 W",
    charging_wireless_w: "25 W",
    cellular: "5G",
    wifi_gen: "Wi-Fi 7",
    usb_standard: "USB-C",
    sim_config: "Nano-SIM + eSIM",
    ip_rating: "IP68",
    weight_g: "206 g",
    build_materials: "Aluminium unibody, Ceramic Shield 2",
    android_version: "26",
    os_update_years: "7",
    security_update_years: "7",
  },
  "iPhone Air": {
    ...IPHONE_COMMON,
    display_size_in: "6.5 in",
    display_tech: "LTPO OLED",
    display_resolution: "2736 x 1260",
    display_ppi: "460",
    refresh_rate_hz: "120 Hz",
    peak_brightness_nits: "3000 nits",
    chipset: "Apple A19 Pro",
    cpu_cores: "6",
    gpu: "Apple 5-core GPU",
    ram_gb: "12 GB",
    storage_gb: "256 GB",
    main_cam_mp: "48 MP",
    main_cam_ois: "Yes",
    front_cam_mp: "18 MP",
    battery_mah: "3149 mAh",
    charging_wired_w: "20 W",
    charging_wireless_w: "20 W",
    cellular: "5G",
    wifi_gen: "Wi-Fi 7",
    usb_standard: "USB-C",
    sim_config: "eSIM only",
    ip_rating: "IP68",
    weight_g: "165 g",
    build_materials: "Titanium frame, Ceramic Shield 2",
    android_version: "26",
    os_update_years: "7",
    security_update_years: "7",
  },
  "iPhone 17": {
    ...IPHONE_COMMON,
    display_size_in: "6.3 in",
    display_tech: "LTPO OLED",
    display_resolution: "2622 x 1206",
    display_ppi: "460",
    refresh_rate_hz: "120 Hz",
    peak_brightness_nits: "3000 nits",
    chipset: "Apple A19",
    cpu_cores: "6",
    gpu: "Apple 5-core GPU",
    ram_gb: "8 GB",
    storage_gb: "256 GB",
    main_cam_mp: "48 MP",
    main_cam_ois: "Yes",
    ultrawide_mp: "48 MP",
    front_cam_mp: "18 MP",
    battery_mah: "3692 mAh",
    charging_wired_w: "30 W",
    charging_wireless_w: "25 W",
    cellular: "5G",
    wifi_gen: "Wi-Fi 7",
    usb_standard: "USB-C",
    sim_config: "Nano-SIM + eSIM",
    ip_rating: "IP68",
    weight_g: "177 g",
    build_materials: "Aluminium, Ceramic Shield 2",
    android_version: "26",
    os_update_years: "7",
    security_update_years: "7",
  },
  "iPhone 16 Plus": {
    ...IPHONE_COMMON,
    display_size_in: "6.7 in",
    display_tech: "OLED",
    display_resolution: "2796 x 1290",
    display_ppi: "460",
    refresh_rate_hz: "60 Hz",
    peak_brightness_nits: "2000 nits",
    chipset: "Apple A18",
    cpu_cores: "6",
    gpu: "Apple 5-core GPU",
    ram_gb: "8 GB",
    storage_gb: "128 GB",
    main_cam_mp: "48 MP",
    main_cam_ois: "Yes",
    ultrawide_mp: "12 MP",
    front_cam_mp: "12 MP",
    battery_mah: "4674 mAh",
    charging_wired_w: "30 W",
    charging_wireless_w: "25 W",
    cellular: "5G",
    wifi_gen: "Wi-Fi 7",
    usb_standard: "USB-C",
    sim_config: "Nano-SIM + eSIM",
    ip_rating: "IP68",
    weight_g: "199 g",
    build_materials: "Aluminium, Ceramic Shield",
    android_version: "18",
    os_update_years: "6",
    security_update_years: "7",
  },
  "iPhone 16": {
    ...IPHONE_COMMON,
    display_size_in: "6.1 in",
    display_tech: "OLED",
    display_resolution: "2556 x 1179",
    display_ppi: "460",
    refresh_rate_hz: "60 Hz",
    peak_brightness_nits: "2000 nits",
    chipset: "Apple A18",
    cpu_cores: "6",
    gpu: "Apple 5-core GPU",
    ram_gb: "8 GB",
    storage_gb: "128 GB",
    main_cam_mp: "48 MP",
    main_cam_ois: "Yes",
    ultrawide_mp: "12 MP",
    front_cam_mp: "12 MP",
    battery_mah: "3561 mAh",
    charging_wired_w: "30 W",
    charging_wireless_w: "25 W",
    cellular: "5G",
    wifi_gen: "Wi-Fi 7",
    usb_standard: "USB-C",
    sim_config: "Nano-SIM + eSIM",
    ip_rating: "IP68",
    weight_g: "170 g",
    build_materials: "Aluminium, Ceramic Shield",
    android_version: "18",
    os_update_years: "6",
    security_update_years: "7",
  },
  "iPhone 16e": {
    ...IPHONE_COMMON,
    display_size_in: "6.1 in",
    display_tech: "OLED",
    display_resolution: "2532 x 1170",
    display_ppi: "460",
    refresh_rate_hz: "60 Hz",
    peak_brightness_nits: "1200 nits",
    chipset: "Apple A18",
    cpu_cores: "6",
    gpu: "Apple 4-core GPU",
    ram_gb: "8 GB",
    storage_gb: "128 GB",
    main_cam_mp: "48 MP",
    main_cam_ois: "Yes",
    front_cam_mp: "12 MP",
    battery_mah: "4005 mAh",
    charging_wired_w: "20 W",
    charging_wireless_w: "7.5 W",
    cellular: "5G",
    wifi_gen: "Wi-Fi 6",
    usb_standard: "USB-C",
    sim_config: "Nano-SIM + eSIM",
    ip_rating: "IP68",
    weight_g: "167 g",
    build_materials: "Aluminium, Ceramic Shield",
    android_version: "18",
    os_update_years: "6",
    security_update_years: "7",
  },
  "iPhone 15 Plus": {
    ...IPHONE_COMMON,
    display_size_in: "6.7 in",
    display_tech: "OLED",
    display_resolution: "2796 x 1290",
    display_ppi: "460",
    refresh_rate_hz: "60 Hz",
    peak_brightness_nits: "2000 nits",
    chipset: "Apple A16 Bionic",
    cpu_cores: "6",
    gpu: "Apple 5-core GPU",
    ram_gb: "6 GB",
    storage_gb: "128 GB",
    main_cam_mp: "48 MP",
    main_cam_ois: "Yes",
    ultrawide_mp: "12 MP",
    front_cam_mp: "12 MP",
    battery_mah: "4383 mAh",
    charging_wired_w: "20 W",
    charging_wireless_w: "15 W",
    cellular: "5G",
    wifi_gen: "Wi-Fi 6",
    usb_standard: "USB-C",
    sim_config: "Nano-SIM + eSIM",
    ip_rating: "IP68",
    weight_g: "201 g",
    build_materials: "Aluminium, Ceramic Shield",
    android_version: "17",
    os_update_years: "6",
    security_update_years: "6",
  },
  "iPhone 15": {
    ...IPHONE_COMMON,
    display_size_in: "6.1 in",
    display_tech: "OLED",
    display_resolution: "2556 x 1179",
    display_ppi: "460",
    refresh_rate_hz: "60 Hz",
    peak_brightness_nits: "2000 nits",
    chipset: "Apple A16 Bionic",
    cpu_cores: "6",
    gpu: "Apple 5-core GPU",
    ram_gb: "6 GB",
    storage_gb: "128 GB",
    main_cam_mp: "48 MP",
    main_cam_ois: "Yes",
    ultrawide_mp: "12 MP",
    front_cam_mp: "12 MP",
    battery_mah: "3349 mAh",
    charging_wired_w: "20 W",
    charging_wireless_w: "15 W",
    cellular: "5G",
    wifi_gen: "Wi-Fi 6",
    usb_standard: "USB-C",
    sim_config: "Nano-SIM + eSIM",
    ip_rating: "IP68",
    weight_g: "171 g",
    build_materials: "Aluminium, Ceramic Shield",
    android_version: "17",
    os_update_years: "6",
    security_update_years: "6",
  },
  "iPhone 15 Pro Max": {
    ...IPHONE_COMMON,
    display_size_in: "6.7 in",
    display_tech: "LTPO OLED",
    display_resolution: "2796 x 1290",
    display_ppi: "460",
    refresh_rate_hz: "120 Hz",
    peak_brightness_nits: "2000 nits",
    chipset: "Apple A17 Pro",
    cpu_cores: "6",
    gpu: "Apple 6-core GPU",
    ram_gb: "8 GB",
    storage_gb: "256 GB",
    main_cam_mp: "48 MP",
    main_cam_ois: "Yes",
    ultrawide_mp: "12 MP",
    telephoto_mp: "12 MP",
    telephoto_zoom_x: "5x",
    front_cam_mp: "12 MP",
    battery_mah: "4441 mAh",
    charging_wired_w: "27 W",
    charging_wireless_w: "15 W",
    cellular: "5G",
    wifi_gen: "Wi-Fi 6E",
    usb_standard: "USB-C",
    sim_config: "Nano-SIM + eSIM",
    ip_rating: "IP68",
    weight_g: "221 g",
    build_materials: "Titanium frame, Ceramic Shield",
    android_version: "17",
    os_update_years: "6",
    security_update_years: "6",
  },
  "iPhone 14 Pro Max": {
    ...IPHONE_COMMON,
    display_size_in: "6.7 in",
    display_tech: "LTPO OLED",
    display_resolution: "2796 x 1290",
    display_ppi: "460",
    refresh_rate_hz: "120 Hz",
    peak_brightness_nits: "2000 nits",
    chipset: "Apple A16 Bionic",
    cpu_cores: "6",
    gpu: "Apple 5-core GPU",
    ram_gb: "6 GB",
    storage_gb: "256 GB",
    main_cam_mp: "48 MP",
    main_cam_ois: "Yes",
    ultrawide_mp: "12 MP",
    telephoto_mp: "12 MP",
    telephoto_zoom_x: "3x",
    front_cam_mp: "12 MP",
    battery_mah: "4323 mAh",
    charging_wired_w: "27 W",
    charging_wireless_w: "15 W",
    cellular: "5G",
    wifi_gen: "Wi-Fi 6",
    usb_standard: "Lightning",
    sim_config: "Nano-SIM + eSIM",
    ip_rating: "IP68",
    weight_g: "240 g",
    build_materials: "Stainless steel frame, Ceramic Shield",
    android_version: "16",
    os_update_years: "5",
    security_update_years: "6",
  },
  "iPhone 14 Pro": {
    ...IPHONE_COMMON,
    display_size_in: "6.1 in",
    display_tech: "LTPO OLED",
    display_resolution: "2556 x 1179",
    display_ppi: "460",
    refresh_rate_hz: "120 Hz",
    peak_brightness_nits: "2000 nits",
    chipset: "Apple A16 Bionic",
    cpu_cores: "6",
    gpu: "Apple 5-core GPU",
    ram_gb: "6 GB",
    storage_gb: "256 GB",
    main_cam_mp: "48 MP",
    main_cam_ois: "Yes",
    ultrawide_mp: "12 MP",
    telephoto_mp: "12 MP",
    telephoto_zoom_x: "3x",
    front_cam_mp: "12 MP",
    battery_mah: "3200 mAh",
    charging_wired_w: "27 W",
    charging_wireless_w: "15 W",
    cellular: "5G",
    wifi_gen: "Wi-Fi 6",
    usb_standard: "Lightning",
    sim_config: "Nano-SIM + eSIM",
    ip_rating: "IP68",
    weight_g: "206 g",
    build_materials: "Stainless steel frame, Ceramic Shield",
    android_version: "16",
    os_update_years: "5",
    security_update_years: "6",
  },
  "iPhone 14": {
    ...IPHONE_COMMON,
    display_size_in: "6.1 in",
    display_tech: "OLED",
    display_resolution: "2532 x 1170",
    display_ppi: "460",
    refresh_rate_hz: "60 Hz",
    peak_brightness_nits: "1200 nits",
    chipset: "Apple A15 Bionic",
    cpu_cores: "6",
    gpu: "Apple 5-core GPU",
    ram_gb: "6 GB",
    storage_gb: "128 GB",
    main_cam_mp: "12 MP",
    main_cam_ois: "Yes",
    ultrawide_mp: "12 MP",
    front_cam_mp: "12 MP",
    battery_mah: "3279 mAh",
    charging_wired_w: "20 W",
    charging_wireless_w: "15 W",
    cellular: "5G",
    wifi_gen: "Wi-Fi 6",
    usb_standard: "Lightning",
    sim_config: "Nano-SIM + eSIM",
    ip_rating: "IP68",
    weight_g: "172 g",
    build_materials: "Aluminium, Ceramic Shield",
    android_version: "16",
    os_update_years: "5",
    security_update_years: "6",
  },
  "iPhone 13 Pro Max": {
    ...IPHONE_COMMON,
    display_size_in: "6.7 in",
    display_tech: "LTPO OLED",
    display_resolution: "2778 x 1284",
    display_ppi: "458",
    refresh_rate_hz: "120 Hz",
    peak_brightness_nits: "1200 nits",
    chipset: "Apple A15 Bionic",
    cpu_cores: "6",
    gpu: "Apple 5-core GPU",
    ram_gb: "6 GB",
    storage_gb: "256 GB",
    main_cam_mp: "12 MP",
    main_cam_ois: "Yes",
    ultrawide_mp: "12 MP",
    telephoto_mp: "12 MP",
    telephoto_zoom_x: "3x",
    front_cam_mp: "12 MP",
    battery_mah: "4352 mAh",
    charging_wired_w: "27 W",
    charging_wireless_w: "15 W",
    cellular: "5G",
    wifi_gen: "Wi-Fi 6",
    usb_standard: "Lightning",
    sim_config: "Nano-SIM + eSIM",
    ip_rating: "IP68",
    weight_g: "240 g",
    build_materials: "Stainless steel frame, Ceramic Shield",
    android_version: "15",
    os_update_years: "5",
    security_update_years: "6",
  },
  "iPhone 13 Pro": {
    ...IPHONE_COMMON,
    display_size_in: "6.1 in",
    display_tech: "LTPO OLED",
    display_resolution: "2532 x 1170",
    display_ppi: "460",
    refresh_rate_hz: "120 Hz",
    peak_brightness_nits: "1200 nits",
    chipset: "Apple A15 Bionic",
    cpu_cores: "6",
    gpu: "Apple 5-core GPU",
    ram_gb: "6 GB",
    storage_gb: "256 GB",
    main_cam_mp: "12 MP",
    main_cam_ois: "Yes",
    ultrawide_mp: "12 MP",
    telephoto_mp: "12 MP",
    telephoto_zoom_x: "3x",
    front_cam_mp: "12 MP",
    battery_mah: "3095 mAh",
    charging_wired_w: "23 W",
    charging_wireless_w: "15 W",
    cellular: "5G",
    wifi_gen: "Wi-Fi 6",
    usb_standard: "Lightning",
    sim_config: "Nano-SIM + eSIM",
    ip_rating: "IP68",
    weight_g: "204 g",
    build_materials: "Stainless steel frame, Ceramic Shield",
    android_version: "15",
    os_update_years: "5",
    security_update_years: "6",
  },
  "iPhone 13": {
    ...IPHONE_COMMON,
    display_size_in: "6.1 in",
    display_tech: "OLED",
    display_resolution: "2532 x 1170",
    display_ppi: "460",
    refresh_rate_hz: "60 Hz",
    peak_brightness_nits: "1200 nits",
    chipset: "Apple A15 Bionic",
    cpu_cores: "6",
    gpu: "Apple 4-core GPU",
    ram_gb: "4 GB",
    storage_gb: "128 GB",
    main_cam_mp: "12 MP",
    main_cam_ois: "Yes",
    ultrawide_mp: "12 MP",
    front_cam_mp: "12 MP",
    battery_mah: "3240 mAh",
    charging_wired_w: "20 W",
    charging_wireless_w: "15 W",
    cellular: "5G",
    wifi_gen: "Wi-Fi 6",
    usb_standard: "Lightning",
    sim_config: "Nano-SIM + eSIM",
    ip_rating: "IP68",
    weight_g: "174 g",
    build_materials: "Aluminium, Ceramic Shield",
    android_version: "15",
    os_update_years: "5",
    security_update_years: "6",
  },
  "iPhone 12 Pro Max": {
    ...IPHONE_COMMON,
    display_size_in: "6.7 in",
    display_tech: "OLED",
    display_resolution: "2778 x 1284",
    display_ppi: "458",
    refresh_rate_hz: "60 Hz",
    peak_brightness_nits: "1200 nits",
    chipset: "Apple A14 Bionic",
    cpu_cores: "6",
    gpu: "Apple 4-core GPU",
    ram_gb: "6 GB",
    storage_gb: "256 GB",
    main_cam_mp: "12 MP",
    main_cam_ois: "Yes",
    ultrawide_mp: "12 MP",
    telephoto_mp: "12 MP",
    telephoto_zoom_x: "2.5x",
    front_cam_mp: "12 MP",
    battery_mah: "3687 mAh",
    charging_wired_w: "20 W",
    charging_wireless_w: "15 W",
    cellular: "5G",
    wifi_gen: "Wi-Fi 6",
    usb_standard: "Lightning",
    sim_config: "Nano-SIM + eSIM",
    ip_rating: "IP68",
    weight_g: "228 g",
    build_materials: "Stainless steel frame, Ceramic Shield",
    android_version: "14",
    os_update_years: "5",
    security_update_years: "6",
  },
  "iPhone 12 Pro": {
    ...IPHONE_COMMON,
    display_size_in: "6.1 in",
    display_tech: "OLED",
    display_resolution: "2532 x 1170",
    display_ppi: "460",
    refresh_rate_hz: "60 Hz",
    peak_brightness_nits: "1200 nits",
    chipset: "Apple A14 Bionic",
    cpu_cores: "6",
    gpu: "Apple 4-core GPU",
    ram_gb: "6 GB",
    storage_gb: "128 GB",
    main_cam_mp: "12 MP",
    main_cam_ois: "Yes",
    ultrawide_mp: "12 MP",
    telephoto_mp: "12 MP",
    telephoto_zoom_x: "2x",
    front_cam_mp: "12 MP",
    battery_mah: "2815 mAh",
    charging_wired_w: "20 W",
    charging_wireless_w: "15 W",
    cellular: "5G",
    wifi_gen: "Wi-Fi 6",
    usb_standard: "Lightning",
    sim_config: "Nano-SIM + eSIM",
    ip_rating: "IP68",
    weight_g: "187 g",
    build_materials: "Stainless steel frame, Ceramic Shield",
    android_version: "14",
    os_update_years: "5",
    security_update_years: "6",
  },
  "iPhone 12": {
    ...IPHONE_COMMON,
    display_size_in: "6.1 in",
    display_tech: "OLED",
    display_resolution: "2532 x 1170",
    display_ppi: "460",
    refresh_rate_hz: "60 Hz",
    peak_brightness_nits: "1200 nits",
    chipset: "Apple A14 Bionic",
    cpu_cores: "6",
    gpu: "Apple 4-core GPU",
    ram_gb: "4 GB",
    storage_gb: "64 GB",
    main_cam_mp: "12 MP",
    main_cam_ois: "Yes",
    ultrawide_mp: "12 MP",
    front_cam_mp: "12 MP",
    battery_mah: "2815 mAh",
    charging_wired_w: "20 W",
    charging_wireless_w: "15 W",
    cellular: "5G",
    wifi_gen: "Wi-Fi 6",
    usb_standard: "Lightning",
    sim_config: "Nano-SIM + eSIM",
    ip_rating: "IP68",
    weight_g: "164 g",
    build_materials: "Aluminium, Ceramic Shield",
    android_version: "14",
    os_update_years: "5",
    security_update_years: "6",
  },
  "iPhone 11 Pro Max": {
    ...IPHONE_COMMON,
    display_size_in: "6.5 in",
    display_tech: "OLED",
    display_resolution: "2688 x 1242",
    display_ppi: "458",
    refresh_rate_hz: "60 Hz",
    peak_brightness_nits: "800 nits",
    chipset: "Apple A13 Bionic",
    cpu_cores: "6",
    gpu: "Apple 4-core GPU",
    ram_gb: "4 GB",
    storage_gb: "256 GB",
    main_cam_mp: "12 MP",
    main_cam_ois: "Yes",
    ultrawide_mp: "12 MP",
    telephoto_mp: "12 MP",
    telephoto_zoom_x: "2x",
    front_cam_mp: "12 MP",
    battery_mah: "3969 mAh",
    charging_wired_w: "18 W",
    charging_wireless_w: "7.5 W",
    cellular: "4G",
    wifi_gen: "Wi-Fi 6",
    usb_standard: "Lightning",
    sim_config: "Nano-SIM + eSIM",
    ip_rating: "IP68",
    weight_g: "226 g",
    build_materials: "Stainless steel frame, glass back",
    android_version: "13",
    os_update_years: "6",
    security_update_years: "6",
  },
  "iPhone 11 Pro": {
    ...IPHONE_COMMON,
    display_size_in: "5.8 in",
    display_tech: "OLED",
    display_resolution: "2436 x 1125",
    display_ppi: "458",
    refresh_rate_hz: "60 Hz",
    peak_brightness_nits: "800 nits",
    chipset: "Apple A13 Bionic",
    cpu_cores: "6",
    gpu: "Apple 4-core GPU",
    ram_gb: "4 GB",
    storage_gb: "256 GB",
    main_cam_mp: "12 MP",
    main_cam_ois: "Yes",
    ultrawide_mp: "12 MP",
    telephoto_mp: "12 MP",
    telephoto_zoom_x: "2x",
    front_cam_mp: "12 MP",
    battery_mah: "3046 mAh",
    charging_wired_w: "18 W",
    charging_wireless_w: "7.5 W",
    cellular: "4G",
    wifi_gen: "Wi-Fi 6",
    usb_standard: "Lightning",
    sim_config: "Nano-SIM + eSIM",
    ip_rating: "IP68",
    weight_g: "188 g",
    build_materials: "Stainless steel frame, glass back",
    android_version: "13",
    os_update_years: "6",
    security_update_years: "6",
  },
  "iPhone 11": {
    ...IPHONE_COMMON,
    display_size_in: "6.1 in",
    display_tech: "IPS LCD",
    display_resolution: "1792 x 828",
    display_ppi: "326",
    refresh_rate_hz: "60 Hz",
    peak_brightness_nits: "625 nits",
    chipset: "Apple A13 Bionic",
    cpu_cores: "6",
    gpu: "Apple 4-core GPU",
    ram_gb: "4 GB",
    storage_gb: "128 GB",
    main_cam_mp: "12 MP",
    main_cam_ois: "Yes",
    ultrawide_mp: "12 MP",
    front_cam_mp: "12 MP",
    battery_mah: "3110 mAh",
    charging_wired_w: "18 W",
    charging_wireless_w: "7.5 W",
    cellular: "4G",
    wifi_gen: "Wi-Fi 6",
    usb_standard: "Lightning",
    sim_config: "Nano-SIM + eSIM",
    ip_rating: "IP68",
    weight_g: "194 g",
    build_materials: "Aluminium frame, glass back",
    android_version: "13",
    os_update_years: "6",
    security_update_years: "6",
  },
  "iPhone X": {
    ...IPHONE_COMMON,
    display_size_in: "5.8 in",
    display_tech: "OLED",
    display_resolution: "2436 x 1125",
    display_ppi: "458",
    refresh_rate_hz: "60 Hz",
    peak_brightness_nits: "625 nits",
    chipset: "Apple A11 Bionic",
    cpu_cores: "6",
    gpu: "Apple 3-core GPU",
    ram_gb: "3 GB",
    storage_gb: "256 GB",
    main_cam_mp: "12 MP",
    main_cam_ois: "Yes",
    telephoto_mp: "12 MP",
    telephoto_zoom_x: "2x",
    front_cam_mp: "7 MP",
    battery_mah: "2716 mAh",
    charging_wired_w: "15 W",
    charging_wireless_w: "7.5 W",
    cellular: "4G",
    wifi_gen: "Wi-Fi 5",
    usb_standard: "Lightning",
    sim_config: "Nano-SIM",
    ip_rating: "IP67",
    weight_g: "174 g",
    build_materials: "Stainless steel frame, glass back",
    android_version: "11",
    os_update_years: "6",
    security_update_years: "6",
  },
};

/** Shopify handle -> the model it is (and identity fields). Covers both the new Apple line and the Ex-UK units. */
export const SMARTPHONE_SEED: Record<
  string,
  { shopifyProductId: string; model: string; releaseYear: number }
> = {
  // Apple's current line
  "apple-iphone-17-pro-max": { shopifyProductId: "gid://shopify/Product/7749352620099", model: "iPhone 17 Pro Max", releaseYear: 2025 },
  "apple-iphone-17-pro": { shopifyProductId: "gid://shopify/Product/7749352652867", model: "iPhone 17 Pro", releaseYear: 2025 },
  "apple-iphone-17": { shopifyProductId: "gid://shopify/Product/7749352685635", model: "iPhone 17", releaseYear: 2025 },
  "apple-iphone-air": { shopifyProductId: "gid://shopify/Product/7737521307715", model: "iPhone Air", releaseYear: 2025 },
  "apple-iphone-16-plus": { shopifyProductId: "gid://shopify/Product/7749436932163", model: "iPhone 16 Plus", releaseYear: 2024 },
  "apple-iphone-16": { shopifyProductId: "gid://shopify/Product/7749437030467", model: "iPhone 16", releaseYear: 2024 },
  "apple-iphone-16e": { shopifyProductId: "gid://shopify/Product/7749437096003", model: "iPhone 16e", releaseYear: 2025 },
  "apple-iphone-15-plus": { shopifyProductId: "gid://shopify/Product/7749437128771", model: "iPhone 15 Plus", releaseYear: 2023 },
  "apple-iphone-15": { shopifyProductId: "gid://shopify/Product/7749437194307", model: "iPhone 15", releaseYear: 2023 },
  "apple-iphone-14": { shopifyProductId: "gid://shopify/Product/7749437259843", model: "iPhone 14", releaseYear: 2022 },
  "apple-iphone-13": { shopifyProductId: "gid://shopify/Product/7749437292611", model: "iPhone 13", releaseYear: 2021 },

  // Ex-UK units — same device, same specs
  "iphone-15-pro-max": { shopifyProductId: "gid://shopify/Product/7797935112259", model: "iPhone 15 Pro Max", releaseYear: 2023 },
  "iphone-15": { shopifyProductId: "gid://shopify/Product/7797935243331", model: "iPhone 15", releaseYear: 2023 },
  "iphone-14-pro-max": { shopifyProductId: "gid://shopify/Product/7797935374403", model: "iPhone 14 Pro Max", releaseYear: 2022 },
  "iphone-14-pro": { shopifyProductId: "gid://shopify/Product/7797935571011", model: "iPhone 14 Pro", releaseYear: 2022 },
  "iphone-14": { shopifyProductId: "gid://shopify/Product/7797935865923", model: "iPhone 14", releaseYear: 2022 },
  "iphone-13-pro-max-1": { shopifyProductId: "gid://shopify/Product/7797937209411", model: "iPhone 13 Pro Max", releaseYear: 2021 },
  "iphone-13-pro": { shopifyProductId: "gid://shopify/Product/7797936586819", model: "iPhone 13 Pro", releaseYear: 2021 },
  "iphone-13": { shopifyProductId: "gid://shopify/Product/7797936685123", model: "iPhone 13", releaseYear: 2021 },
  "iphone-12-pro-max": { shopifyProductId: "gid://shopify/Product/7797936881731", model: "iPhone 12 Pro Max", releaseYear: 2020 },
  "iphone-12-pro": { shopifyProductId: "gid://shopify/Product/7797936980035", model: "iPhone 12 Pro", releaseYear: 2020 },
  "iphone-12": { shopifyProductId: "gid://shopify/Product/7797937438787", model: "iPhone 12", releaseYear: 2020 },
  "iphone-11-pro-max": { shopifyProductId: "gid://shopify/Product/7797937537091", model: "iPhone 11 Pro Max", releaseYear: 2019 },
  "iphone-11-pro": { shopifyProductId: "gid://shopify/Product/7797937700931", model: "iPhone 11 Pro", releaseYear: 2019 },
  "iphone-11": { shopifyProductId: "gid://shopify/Product/7797937832003", model: "iPhone 11", releaseYear: 2019 },
  "iphone-x": { shopifyProductId: "gid://shopify/Product/7797937930307", model: "iPhone X", releaseYear: 2017 },
};
